FROM python:3.10-slim

WORKDIR /app

COPY src/frontend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src/frontend /app/frontend

ENV PYTHONPATH=/app
ENV BACKEND_URL=http://appetite-backend:8000

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]